language: generic
sudo: required
  - docker

before_install:
  - docker build -t jfiz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jfiz/react-test npm test

after_success:
  - docker build -t jfiz/complex-client ./client
  - docker build -t jfiz/complex-nginx ./nginx
  - docker build -t jfiz/complex-server ./server
  - docker build -t jfiz/complex-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jfiz/complex-client
  - docker push jfiz/complex-nginx
  - docker push jfiz/complex-server
  - docker push jfiz/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-221001040474
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY